-- FIN DE LA ESTRUCTURA SOLICITADA PARA MANEJO CON UN ADMIN, UNO QUE INGRESA, SELECCIONA O MODIFICA Y UNO QUE CREA VISTAS.
--DESDE MI ADMIN ORACLE
CREATE USER user_administrador 
IDENTIFIED BY "AdminCNA.2025" 
DEFAULT TABLESPACE DATA  -- TABLESPACE ORACLE CLOUD 
QUOTA UNLIMITED ON DATA;

--CREO AL ADMINISTRADOR CON SU ROL
CREATE ROLE role_administrador;--SERA EL DUENIO DE LOS DATOS SOLO POR DEBAJO DEL ADMIN DBA
GRANT CONNECT, RESOURCE TO role_administrador; -- ASINGNACION DE PERMISOS DEL ROL ADMINISTRADOR
GRANT role_administrador TO user_administrador; -- AGREGO EL ROL AL ADMINISTRADOR
GRANT EXECUTE ON SYS.DBMS_STATS TO role_administrador; --AGREGO PERMISO AL ROL PARA QUE EJECUTE ESTADISTICAS

--CREO 2 ROLES DE AYUDANTES
CREATE ROLE role_analista; -- SERA QUIEN PUEDA INSERTAR, SELECCIONAR U MODIFICAR LOS DATOS DE LAS TABLAS
CREATE ROLE role_vistas; --PUEDE CREAR VISTAS

-- LE DOY PERMISOS
GRANT CONNECT TO role_analista; --PRA QUE SE PUEDA CONECTAR DESDE EL USER_ADMINISTRADOR SE LE DARA LOS PERMISOS SOBRE LAS TABLAS
GRANT CONNECT, CREATE VIEW TO role_vistas; --PODRA CREAR LAS VISTAS QUE CONSIDERE NECESARIAS

--CREO LOS 2 USUSARIO QUE AYUDARAN
CREATE USER user_analista 
IDENTIFIED BY "AnalistaCNA.2025" 
DEFAULT TABLESPACE DATA  -- TABLESPACE ORACLE CLOUD 
QUOTA UNLIMITED ON DATA;
GRANT role_analista TO user_analista; --ASIGNO ROLE

CREATE USER user_vistas 
IDENTIFIED BY "VistasCNA.2025" 
DEFAULT TABLESPACE DATA  -- TABLESPACE ORACLE CLOUD 
QUOTA UNLIMITED ON DATA;
GRANT role_vistas TO user_vistas; --ASIGNO ROLE

SELECT * FROM DBA_ROLES WHERE ROLE LIKE 'ROLE%'; --COMPRUEBO QUE ESTEN CREADOS LOS ROLES QUE DEFINI
-- COMPRUEBO QUE SE CREARON LOS USERS
SELECT * FROM dba_users WHERE USERNAME = 'USER_ADMINISTRADOR'; 
SELECT * FROM dba_users WHERE USERNAME = 'USER_ANALISTA'; 
SELECT * FROM dba_users WHERE USERNAME = 'USER_VISTAS'; 
-- ME CONECTO CON EL NUEVO user_administrador
-- EJECUTO EL SCRIP DE CREACION Y POBLACION DE LOS DATOS

-- LE DOY LOS PERMISOS A LOS NUEVSO USUARIOS EN SUS ROLES INDIVIDUALES DE FORMA PROCEDURAL
BEGIN
  FOR t IN (
    SELECT table_name 
    FROM user_tables
  ) LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT, INSERT, UPDATE ON ' || t.table_name || ' TO ROLE_ANALISTA';
    EXECUTE IMMEDIATE 'GRANT SELECT ON ' || t.table_name || ' TO ROLE_VISTAS';
  END LOOP;
END;
-- FIN DE LA ESTRUCTURA SOLICITADA PARA MANEJO CON UN ADMIN, UNO QUE INGRESA, SELECCIONA O MODIFICA Y UNO QUE CREA VISTAS.
-- SE PODRIA CREAR UNA FUNCION PERSONALIZADA PARA VALIDAR UN  PASSWORD SEGURO, PERO ORACLE TIENE EL CONTROL
CREATE OR REPLACE FUNCTION fn_valida_password (
    username VARCHAR2,
    password VARCHAR2,
    old_password VARCHAR2
) RETURN BOOLEAN IS
BEGIN
  -- Longitud mínima
  IF LENGTH(password) < 10 THEN
    RAISE_APPLICATION_ERROR(-20001, 'La contraseña debe tener al menos 10 caracteres.');
  END IF;

  -- Debe contener al menos una letra mayúscula
  IF NOT REGEXP_LIKE(password, '[A-Z]') THEN
    RAISE_APPLICATION_ERROR(-20002, 'La contraseña debe tener al menos una letra mayúscula.');
  END IF;

  -- Debe contener al menos una letra minúscula
  IF NOT REGEXP_LIKE(password, '[a-z]') THEN
    RAISE_APPLICATION_ERROR(-20003, 'La contraseña debe tener al menos una letra minúscula.');
  END IF;

  -- Debe contener al menos un número
  IF NOT REGEXP_LIKE(password, '[0-9]') THEN
    RAISE_APPLICATION_ERROR(-20004, 'La contraseña debe tener al menos un número.');
  END IF;

  -- No debe contener el nombre de usuario
  IF INSTR(LOWER(password), LOWER(username)) > 0 THEN
    RAISE_APPLICATION_ERROR(-20005, 'La contraseña no puede contener el nombre de usuario.');
  END IF;

-- Debe contener al menos un carácter especial
IF NOT REGEXP_LIKE(password, '[!@#$%^&*()_+\-=\[\]{};:"\\|,.<>\/?]') THEN
  RAISE_APPLICATION_ERROR(-20006, 'La contraseña debe tener al menos un caracter especial.');
END IF;

  RETURN TRUE;
END;


--OBTENGO EL PERFIL
SELECT u.username, du.profile
FROM all_users u
JOIN dba_users du ON u.username = du.username
WHERE u.username = USER;

--OBTEGNO LOS PERMISOS DEFINIDOS EN EL PROFILE
SELECT * 
FROM dba_profiles 
WHERE profile = 'ORA_ADMIN_PROFILE';

--PODRIA CREAR UN PERFIL PARA EL PROYECTO, ORACLE CLOUD NO PERMITE CAMBIAR LA POLITICA DE PASSWORD PARA CREAR UNA PERSONALIZADA
CREATE PROFILE perfil_CNA_Chile_S8
LIMIT
  FAILED_LOGIN_ATTEMPTS 5 --CON 5 INTENTOS DE INICIO FALLIDOS SE BLOQUEA LA CUENTA
  PASSWORD_LIFE_TIME 20 -- LA CONTRASENIA SERA VALIDA POR 20 DIAS
  PASSWORD_LOCK_TIME 1 -- ESTARA BLOQUEADA 1 DIA
  PASSWORD_REUSE_TIME 180 -- UNA MISMA CONTRASENIA NO PUEDE SER USADA EN MENOS DE 180 DIAS
  PASSWORD_REUSE_MAX 5 -- NO SE PUEDEN REUTILIZAR LAS ULTIMAS 5 CONTRASENIAS
  -- PASSWORD_VERIFY_FUNCTION fn_valida_password --NO SE DEFINE PERSONALIZADA POR ORACLE CLOUD QUE LO HACE SOLO EL DE FOR
  -- PASSWORD_REUSE_TIME UNLIMITED --SI NO NOS IMPORTARA QUE USE LA MISMA CONTRASENIA VARIAS VECES
  SESSIONS_PER_USER 2; -- PUEDE TENER 2 SESIONES ABIERTAS DE FORMA SIMULTANEA
  

