/* 
 * FORMATO DE RESPUESTA 
 * SCRIPT SQL 
 * ACTIVIDAD SEMANAL
 * 
 * En esta tercera semana realizarás la actividad formativa individual,
 * llamada Trabajando con funciones SQL de una fila y con grupos de filas, 
 * la cual consta de dos partes.  
 * 
 * En la primera parte, deberás resolver un caso para construir sentencias SQL 
 * usando funciones SQL de una fila y grupos de filas.  
 * 
 * En la segunda parte, deberás desarrollar un Quiz con preguntas de selección única 
 * basadas en el desarrollo del caso planteado. 
 *
 * A continuación, documenta de forma ordenada y con comentarios
 * cada una de las partes del código a desarrollar. 
 * 
 * Script de sentencias SQL requeridas. 
 * 
 */
 --Inicio de la consulta
SELECT 
    EXTRACT(YEAR FROM L.FECHA_OTORGAMIENTO) AS "Consulta", --EXTRAEMOS EL ANIO DE UNA FECHA
    CASE L.ID_TIPO_LIC 
        WHEN 1 THEN 'Accidente comun'
        WHEN 5 THEN 'Accidente laboral'
        WHEN 6 THEN 'Enfermedad profesional'
    END AS "Tipo Licencia", --RENOMBRAMOS DE FORMA MANUAL LOS INDICES
    -- DE AQUI EN ADELANTO AGREGAMOS SEPARADOR DE MILES DONDE LA G ES EL PUNTO Y CON LPAD() AGREGAMOS ESPACIOS HASTA 12 DIGITOS PARA QUE SE VEAN A LA DERECHA
    LPAD(TO_CHAR(COUNT(L.ID_LICENCIA), 'FM999G999G999'), 12) AS "Num. licencias", --CONTAMOS LA CANTIDAD DE LICENCIAS
    LPAD(TO_CHAR(SUM(TO_DATE(FECHA_REPOSO_FIN,'DD/MM/YYYY') - TO_DATE(FECHA_REPOSO_INICIO,'DD/MM/YYYY')), 'FM999G999G999'), 12) AS "Dias perdidos", -- SUMAMOS EL TOTAL DE LOS DIASPERDIDOS
    LPAD(TO_CHAR(COUNT(CASE WHEN (TRAYECTO_ACCIDENTE IS NOT NULL AND LUGAR_OTRO IS NULL) THEN 1 END), 'FM999G999G999'), 12) AS "Resp. Mutual", --SUMAMOS LOS QUE PERTENECEN SOLO A LA LUTUAL
    LPAD(TO_CHAR(SUM(CASE 
        WHEN (TRAYECTO_ACCIDENTE IS NOT NULL AND LUGAR_OTRO IS NULL) THEN 
            CASE WHEN FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO < 11 THEN 
                (FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO)-3 
            ELSE FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO END 
        ELSE 0 
    END), 'FM999G999G999'), 12) AS "Dias pago Mutual", --APLICAMOS LA REGLA DE DIAS QUE SERAN CONTABILIZADOS PARA EL PAGO DE LA MUTUAL
    LPAD(TO_CHAR(COUNT(CASE WHEN (TRAYECTO_ACCIDENTE IS NULL OR LUGAR_OTRO IS NOT NULL) THEN 1 END), 'FM999G999G999'), 12) AS "Resp. Entidad Salud", --CONTABILIZAMOS LICENCIAS PARA LA ENTIDAD
    LPAD(TO_CHAR(SUM(CASE 
        WHEN (TRAYECTO_ACCIDENTE IS NULL OR LUGAR_OTRO IS NOT NULL) THEN 
            CASE WHEN FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO < 11 THEN 
                (FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO)-3 
            ELSE FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO END 
        ELSE 0 
    END), 'FM999G999G999'), 12) AS "Dias Pago Entidad Salud",--APLICAMOS LA REGLA DE DIAS QUE SERAN CONTABILIZADOS PARA EL PAGO DE LA ENTIDAD
    LPAD(TO_CHAR(SUM(CASE 
        WHEN (TRAYECTO_ACCIDENTE IS NOT NULL AND LUGAR_OTRO IS NULL) THEN 
            CASE WHEN FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO < 11 THEN 
                (FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO)-3 
            ELSE FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO END
        WHEN (TRAYECTO_ACCIDENTE IS NULL OR LUGAR_OTRO IS NOT NULL) THEN 
            CASE WHEN FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO < 11 THEN 
                (FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO)-3 
            ELSE FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO END
        ELSE 0 
    END), 'FM999G999G999'), 12) AS "Dias Pagados", --SUMAMOS LA TOTALIDAD DE DIAS PAGADOS
    LPAD(TO_CHAR(
        SUM(TO_DATE(FECHA_REPOSO_FIN,'DD/MM/YYYY') - TO_DATE(FECHA_REPOSO_INICIO,'DD/MM/YYYY')) - 
        SUM(CASE 
            WHEN (TRAYECTO_ACCIDENTE IS NOT NULL AND LUGAR_OTRO IS NULL) THEN 
                CASE WHEN FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO < 11 THEN 
                    (FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO)-3 
                ELSE FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO END
            WHEN (TRAYECTO_ACCIDENTE IS NULL OR LUGAR_OTRO IS NOT NULL) THEN 
                CASE WHEN FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO < 11 THEN 
                    (FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO)-3 
                ELSE FECHA_REPOSO_FIN - FECHA_REPOSO_INICIO END
            ELSE 0 
        END),
    'FM999G999G999'), 12) AS "Dias NO Pagados" -- DE LA TOTALIDAD DE DIAS PERDIDOS POR LICENCIAS RESTAMOS LA TOTALIDAD DE DIAS PAGADOS
FROM LICENCIA L
INNER JOIN TIPO_LICENCIA TL 
    ON TL.ID_TIPO_LICENCIA = L.ID_TIPO_LIC  --HACEMOS JOIN DE CON LA TABLA TIPO LICENCIAS
WHERE EXTRACT(YEAR FROM L.FECHA_OTORGAMIENTO) IN (2023, 2024)  --BUSCAMOS SOLO LOS 2 ANIOS ANTERIORES
AND L.ID_TIPO_LIC IN (1,5,6)  -- Y LAS LICENCIAS QUE TIENEN ESTOS INDICES
GROUP BY EXTRACT(YEAR FROM L.FECHA_OTORGAMIENTO), L.ID_TIPO_LIC  --AGRUPAMOS POR ANIO Y DESPUES TIPO DE LICENCIA
ORDER BY EXTRACT(YEAR FROM L.FECHA_OTORGAMIENTO) DESC; --ORDENAMOS DESENDENTE POR ANIOS 
